name: Pages deploy 
on:
  push:
    branches:
      - main 
jobs: 
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
      - name: jekyll installation check 
        run: bundle install
        working-directory: docs 
      - name: build site 
        run: bundle exec jekyll build
        working-directory: docs 
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/_site'

  deploy-pages:
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    steps:
      - name: deploy pages
        uses: actions/deploy-pages@v4
